"""Render the committed bootstrap deploy-role stack (rc-kiz.3).

Reuses the same Jinja2 ``TerraformEmitter`` + backend renderer as the workload
provider, so output is deterministic and byte-identical on re-emit. No AWS calls.
"""

from __future__ import annotations

import json
from pathlib import Path

from ..config._schema_types import GithubOidcDeployRole
from ..terraform.backend import render_backend_block
from ..terraform.emitter import TerraformEmitter
from . import build

_TEMPLATE_DIR = Path(__file__).parent / "templates"

# This stack IS committed (the .tf files are tracked). Only terraform's volatile
# artifacts stay out of git — state is NEVER committed.
_GITIGNORE = """# Managed by remote-compose (bootstrap stack). The .tf files in this dir ARE
# committed — this is tracked IaC, not a regenerated workload stack. Only
# terraform's volatile artifacts (provider cache, state, plan files) are
# ignored; state is NEVER committed.
.terraform/
*.tfstate
*.tfstate.backup
*.tfplan
crash.log
crash.*.log
"""

_README_TEMPLATE = """# Bootstrap stack for {project}

Committed CI/bootstrap IaC, generated by remote-compose from the rc.yml
`bootstrap:` section. Unlike the regenerated workload stack
(`deploy/<project>/terraform/`), this stack is COMMITTED and keeps its own
terraform state — the GitHub Actions OIDC deploy role it manages is not a
per-service runtime resource, so it must be tracked rather than regenerated.

## Usage

    rc bootstrap            # emit + terraform plan (read-only)
    rc bootstrap --apply    # emit + terraform apply (opt-in; never destroys)

Or standalone:

    terraform init
    terraform plan
    terraform apply

The AWS region + credentials come from your environment / profile
(`AWS_REGION`, `AWS_PROFILE`), the same as any terraform stack.

## Adopting a live deploy role (import -> no-op)

To bring an existing, hand-managed deploy role under this stack, set
`bootstrap.github_oidc_deploy_role.role_name` to the live role's name and import
it before the first apply:

    terraform import aws_iam_role.deploy <role-name>
    terraform import aws_iam_role_policy.deploy <role-name>:<role-name>-permissions

`rc bootstrap` (plan) should then report no-op (or a minimal, reviewed diff).
"""


def emit_bootstrap_stack(
    role_cfg: GithubOidcDeployRole,
    *,
    project: str,
    cluster: str,
    workload_backend: dict | None,
    out_dir: Path,
) -> Path:
    """Render the bootstrap stack for ``role_cfg`` into ``out_dir``.

    ``${project}`` / ``${cluster}`` placeholders in the role config are resolved
    here; region/account stay as terraform data-source refs.
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    permissions = build.interpolate(
        role_cfg.permissions, project=project, cluster=cluster
    )
    statements = build.derive_statements(permissions)

    role_name = build.interpolate(
        role_cfg.role_name or "${project}-github-deploy",
        project=project,
        cluster=cluster,
    )

    provider_arn_ref = (
        build.OIDC_PROVIDER_ARN_CREATE
        if role_cfg.create_oidc_provider
        else build.OIDC_PROVIDER_ARN_ADOPT
    )
    trust_policy = build.build_trust_policy(
        role_cfg.github_repo, role_cfg.github_branch, provider_arn_ref
    )
    backend = build.derive_bootstrap_backend(workload_backend, project)

    context = {
        "project": project,
        "role_name": role_name,
        "github_oidc_url": build.GITHUB_OIDC_URL,
        "create_oidc_provider": role_cfg.create_oidc_provider,
        "trust_policy_json": json.dumps(trust_policy, indent=2, sort_keys=True),
        "has_statements": bool(statements),
        "policy_json": json.dumps(
            {"Version": "2012-10-17", "Statement": statements},
            indent=2,
            sort_keys=True,
        ),
        "backend_block": render_backend_block(backend),
    }

    TerraformEmitter(_TEMPLATE_DIR).render(context, out_dir)
    (out_dir / "README.md").write_text(_README_TEMPLATE.format(project=project))
    # Only write .gitignore if absent so a hand-tuned one survives re-emit.
    gitignore = out_dir / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(_GITIGNORE)
    return out_dir
