from setuptools import setup, find_packages

setup(
    name='django-remote-compose',
    version='0.1.0',
    description='Django app for deploying Docker Compose to remote hosts via SSH',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    author='Your Name',
    author_email='your.email@example.com',
    url='https://github.com/yourusername/django-remote-compose',
    packages=find_packages(exclude=['tests*']),
    include_package_data=True,
    install_requires=[
        'Django>=4.2,<5.0',
        'paramiko>=3.0.0',
        'cryptography>=41.0.0',
        'boto3>=1.26.0',
        'pyyaml>=6.0',
    ],
    extras_require={
        'celery': ['celery>=5.3.0', 'redis>=5.0.0'],
        'dev': [
            'pytest>=7.4.0',
            'pytest-django>=4.5.0',
            'pytest-cov>=4.1.0',
            'factory-boy>=3.3.0',
            'black>=23.7.0',
            'flake8>=6.1.0',
        ],
    },
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Framework :: Django',
        'Framework :: Django :: 4.2',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
    ],
    python_requires='>=3.9',
)
