# Generated by Django 4.2.26 on 2025-11-28 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('remote_compose', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, help_text='Type of action performed', max_length=100)),
                ('actor', models.CharField(db_index=True, help_text='User or system that performed the action', max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the action occurred')),
                ('resource_type', models.CharField(blank=True, help_text='Type of resource affected (e.g., deployment, target)', max_length=100, null=True)),
                ('resource_id', models.IntegerField(blank=True, help_text='ID of the resource affected', null=True)),
                ('resource_name', models.CharField(blank=True, help_text='Name of the resource affected', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the actor', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string if applicable', null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the action')),
                ('success', models.BooleanField(default=True, help_text='Whether the action succeeded')),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed', null=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'remote_compose_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RenameIndex(
            model_name='deployment',
            new_name='remote_comp_status_dc47af_idx',
            old_name='remote_comp_status_b8e7c6_idx',
        ),
        migrations.RenameIndex(
            model_name='deployment',
            new_name='remote_comp_target__785af3_idx',
            old_name='remote_comp_target__c5aee6_idx',
        ),
        migrations.RenameIndex(
            model_name='deployment',
            new_name='remote_comp_context_9baf18_idx',
            old_name='remote_comp_context_de06b9_idx',
        ),
        migrations.RenameIndex(
            model_name='deployment',
            new_name='remote_comp_project_87e820_idx',
            old_name='remote_comp_project_98b08d_idx',
        ),
        migrations.RenameIndex(
            model_name='deploymentlog',
            new_name='remote_comp_deploym_4fc359_idx',
            old_name='remote_comp_deploym_7b4e08_idx',
        ),
        migrations.RenameIndex(
            model_name='deploymentlog',
            new_name='remote_comp_log_lev_a1e548_idx',
            old_name='remote_comp_log_lev_4c88a5_idx',
        ),
        migrations.RenameIndex(
            model_name='deploymenttarget',
            new_name='remote_comp_target__7fe7e9_idx',
            old_name='remote_comp_target__9f6e5e_idx',
        ),
        migrations.RenameIndex(
            model_name='deploymenttarget',
            new_name='remote_comp_environ_e6fb42_idx',
            old_name='remote_comp_environ_a3a0a4_idx',
        ),
        migrations.RenameIndex(
            model_name='deploymenttarget',
            new_name='remote_comp_aws_ins_1869d0_idx',
            old_name='remote_comp_aws_ins_64b02e_idx',
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='remote_comp_action_d595b0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor'], name='remote_comp_actor_e8db25_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='remote_comp_resourc_ef58f9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='remote_comp_timesta_dec298_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['success'], name='remote_comp_success_652336_idx'),
        ),
    ]
