# Generated by Django 4.2.26 on 2025-11-29 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remote_compose', '0002_add_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECSCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='Unique name for this cluster in remote-compose', max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('aws_cluster_arn', models.CharField(blank=True, db_index=True, help_text='AWS ECS Cluster ARN', max_length=512, null=True, unique=True)),
                ('aws_cluster_name', models.CharField(help_text='Cluster name in AWS ECS', max_length=255)),
                ('aws_region', models.CharField(default='us-east-1', help_text='AWS region where cluster is deployed', max_length=50)),
                ('launch_type', models.CharField(choices=[('fargate', 'AWS Fargate'), ('ec2', 'EC2 Instances')], default='fargate', help_text='Default launch type for services in this cluster', max_length=20)),
                ('is_managed', models.BooleanField(default=True, help_text='Whether this cluster is managed by remote-compose')),
                ('vpc_id', models.CharField(blank=True, help_text='VPC ID for Fargate tasks', max_length=50, null=True)),
                ('subnet_ids', models.JSONField(blank=True, default=list, help_text='List of subnet IDs for task placement')),
                ('security_group_ids', models.JSONField(blank=True, default=list, help_text='List of security group IDs for tasks')),
                ('status', models.CharField(choices=[('pending', 'Pending Creation'), ('active', 'Active'), ('provisioning', 'Provisioning'), ('deprovisioning', 'Deprovisioning'), ('failed', 'Failed'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('task_execution_role_arn', models.CharField(blank=True, help_text='IAM role ARN for ECS task execution', max_length=512, null=True)),
                ('task_role_arn', models.CharField(blank=True, help_text='IAM role ARN for tasks to access AWS services', max_length=512, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('aws_credential', models.ForeignKey(blank=True, help_text='AWS credentials for managing this cluster', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecs_clusters', to='remote_compose.securecredential')),
            ],
            options={
                'verbose_name': 'ECS Cluster',
                'verbose_name_plural': 'ECS Clusters',
                'db_table': 'remote_compose_ecs_clusters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='deploymenttarget',
            name='target_type',
            field=models.CharField(choices=[('ssh', 'SSH Connection'), ('tcp', 'TCP Connection'), ('unix', 'Unix Socket'), ('ecs', 'AWS ECS')], default='ssh', max_length=20),
        ),
        migrations.CreateModel(
            name='ECSTaskDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='Task definition family name', max_length=255)),
                ('aws_task_definition_arn', models.CharField(blank=True, db_index=True, help_text='AWS Task Definition ARN', max_length=512, null=True, unique=True)),
                ('revision', models.IntegerField(default=1, help_text='Task definition revision number')),
                ('source_compose_file', models.TextField(blank=True, help_text='Original docker-compose.yml content')),
                ('source_compose_hash', models.CharField(blank=True, db_index=True, help_text='SHA256 hash of source compose file for change detection', max_length=64, null=True)),
                ('container_definitions', models.JSONField(default=list, help_text='ECS container definitions (converted from compose)')),
                ('cpu', models.CharField(default='256', help_text='CPU units (256 = 0.25 vCPU for Fargate)', max_length=20)),
                ('memory', models.CharField(default='512', help_text='Memory in MB (minimum 512 for Fargate)', max_length=20)),
                ('requires_compatibilities', models.JSONField(default=list, help_text='Required compatibility types (FARGATE, EC2)')),
                ('network_mode', models.CharField(default='awsvpc', help_text='Docker network mode (awsvpc required for Fargate)', max_length=20)),
                ('volumes', models.JSONField(blank=True, default=list, help_text='ECS volume definitions')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('registered', 'Registered in AWS'), ('active', 'Active (in use)'), ('inactive', 'Inactive'), ('deregistered', 'Deregistered')], default='draft', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('cluster', models.ForeignKey(help_text='ECS cluster this task definition belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='task_definitions', to='remote_compose.ecscluster')),
            ],
            options={
                'verbose_name': 'ECS Task Definition',
                'verbose_name_plural': 'ECS Task Definitions',
                'db_table': 'remote_compose_ecs_task_definitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ECSService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='Service name', max_length=255)),
                ('aws_service_arn', models.CharField(blank=True, db_index=True, help_text='AWS ECS Service ARN', max_length=512, null=True, unique=True)),
                ('desired_count', models.IntegerField(default=1, help_text='Desired number of running tasks')),
                ('min_count', models.IntegerField(default=1, help_text='Minimum number of tasks (for auto-scaling)')),
                ('max_count', models.IntegerField(default=10, help_text='Maximum number of tasks (for auto-scaling)')),
                ('running_count', models.IntegerField(default=0, help_text='Current number of running tasks')),
                ('pending_count', models.IntegerField(default=0, help_text='Current number of pending tasks')),
                ('deployment_controller', models.CharField(choices=[('ECS', 'ECS Rolling Update'), ('CODE_DEPLOY', 'AWS CodeDeploy'), ('EXTERNAL', 'External Controller')], default='ECS', max_length=20)),
                ('deployment_minimum_percent', models.IntegerField(default=50, help_text='Minimum healthy percent during deployment')),
                ('deployment_maximum_percent', models.IntegerField(default=200, help_text='Maximum percent during deployment')),
                ('load_balancer_arn', models.CharField(blank=True, help_text='Target group ARN for load balancing', max_length=512, null=True)),
                ('container_name_for_lb', models.CharField(blank=True, help_text='Container name that receives load balancer traffic', max_length=255, null=True)),
                ('container_port_for_lb', models.IntegerField(blank=True, help_text='Container port for load balancer', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('creating', 'Creating'), ('active', 'Active'), ('draining', 'Draining'), ('updating', 'Updating'), ('deleting', 'Deleting'), ('inactive', 'Inactive'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('last_deployment_at', models.DateTimeField(blank=True, help_text='Last successful deployment time', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Last error message if any')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='remote_compose.ecscluster')),
                ('deployments', models.ManyToManyField(blank=True, help_text='Deployment records associated with this service', related_name='ecs_services', to='remote_compose.deployment')),
                ('task_definition', models.ForeignKey(help_text='Active task definition for this service', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='remote_compose.ecstaskdefinition')),
            ],
            options={
                'verbose_name': 'ECS Service',
                'verbose_name_plural': 'ECS Services',
                'db_table': 'remote_compose_ecs_services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deploymenttarget',
            name='ecs_cluster',
            field=models.ForeignKey(blank=True, help_text='ECS cluster for ECS target type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_targets', to='remote_compose.ecscluster'),
        ),
        migrations.AddField(
            model_name='deploymenttarget',
            name='ecs_service',
            field=models.ForeignKey(blank=True, help_text='Default ECS service for deployments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_targets', to='remote_compose.ecsservice'),
        ),
        migrations.AddIndex(
            model_name='ecstaskdefinition',
            index=models.Index(fields=['cluster', 'name'], name='remote_comp_cluster_e32884_idx'),
        ),
        migrations.AddIndex(
            model_name='ecstaskdefinition',
            index=models.Index(fields=['status'], name='remote_comp_status_a5eb93_idx'),
        ),
        migrations.AddIndex(
            model_name='ecstaskdefinition',
            index=models.Index(fields=['source_compose_hash'], name='remote_comp_source__b5e39b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ecstaskdefinition',
            unique_together={('cluster', 'name', 'revision')},
        ),
        migrations.AddIndex(
            model_name='ecsservice',
            index=models.Index(fields=['cluster', 'status'], name='remote_comp_cluster_a0f3fa_idx'),
        ),
        migrations.AddIndex(
            model_name='ecsservice',
            index=models.Index(fields=['status'], name='remote_comp_status_9d3a01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ecsservice',
            unique_together={('cluster', 'name')},
        ),
        migrations.AddIndex(
            model_name='ecscluster',
            index=models.Index(fields=['aws_region', 'status'], name='remote_comp_aws_reg_e4e515_idx'),
        ),
        migrations.AddIndex(
            model_name='ecscluster',
            index=models.Index(fields=['launch_type', 'status'], name='remote_comp_launch__a3b62e_idx'),
        ),
    ]
