# Generated by Django 4.2.26 on 2025-11-29 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remote_compose', '0003_ecscluster_alter_deploymenttarget_target_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EFSFileSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='Friendly name for this file system', max_length=255)),
                ('aws_file_system_id', models.CharField(db_index=True, help_text='AWS EFS File System ID (e.g., fs-12345678)', max_length=50, unique=True)),
                ('aws_region', models.CharField(help_text='AWS region where file system is located', max_length=50)),
                ('vpc_id', models.CharField(help_text='VPC ID where the file system is deployed', max_length=50)),
                ('security_group_id', models.CharField(blank=True, help_text='Security group ID for mount target access', max_length=50, null=True)),
                ('is_managed', models.BooleanField(default=True, help_text='Whether this file system was created by remote-compose')),
                ('access_points', models.JSONField(blank=True, default=dict, help_text='Mapping of volume names to EFS access point IDs')),
                ('mount_targets', models.JSONField(blank=True, default=list, help_text='List of mount target IDs for this file system')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional file system configuration and state')),
                ('aws_credential', models.ForeignKey(blank=True, help_text='AWS credentials for managing this file system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='efs_file_systems', to='remote_compose.securecredential')),
                ('cluster', models.ForeignKey(help_text='ECS cluster this file system is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='efs_file_systems', to='remote_compose.ecscluster')),
            ],
            options={
                'verbose_name': 'EFS File System',
                'verbose_name_plural': 'EFS File Systems',
                'db_table': 'remote_compose_efs_file_systems',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cluster', 'name'], name='remote_comp_cluster_770757_idx'), models.Index(fields=['aws_region'], name='remote_comp_aws_reg_e46675_idx'), models.Index(fields=['vpc_id'], name='remote_comp_vpc_id_bb7ee5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ECRRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='Repository name in ECR', max_length=255)),
                ('aws_repository_arn', models.CharField(db_index=True, help_text='AWS ECR Repository ARN', max_length=512, unique=True)),
                ('aws_repository_uri', models.CharField(help_text='Full URI for pushing/pulling images', max_length=512)),
                ('aws_region', models.CharField(help_text='AWS region where repository is located', max_length=50)),
                ('is_managed', models.BooleanField(default=True, help_text='Whether this repository was created by remote-compose')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional repository configuration and state')),
                ('aws_credential', models.ForeignKey(blank=True, help_text='AWS credentials for accessing this repository', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecr_repositories', to='remote_compose.securecredential')),
                ('cluster', models.ForeignKey(help_text='ECS cluster this repository is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='ecr_repositories', to='remote_compose.ecscluster')),
            ],
            options={
                'verbose_name': 'ECR Repository',
                'verbose_name_plural': 'ECR Repositories',
                'db_table': 'remote_compose_ecr_repositories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cluster', 'name'], name='remote_comp_cluster_2029ad_idx'), models.Index(fields=['aws_region'], name='remote_comp_aws_reg_b49eb5_idx')],
                'unique_together': {('cluster', 'name')},
            },
        ),
    ]
