"""rc compose import — scaffold a starter rc.yml from a docker-compose.yml.

The auto-import path (cli_v2.build_deploy_context) makes rc.yml's
services[] OPTIONAL — compose drives the deploy set with sensible
defaults (cpu=256/memory=512). This command writes a starting-point
rc.yml the user can hand-edit:

  - project + provider + provider_config defaults
  - per-service overrides for things we can detect (public ports, db
    services with a volume hint, worker-shaped names)
  - inline comments showing env_file refs the user may want to
    declare as secrets

It's a 30-second migration of "I have docker-compose.yml, what do I
type next?" into a runnable rc.yml.
"""

from __future__ import annotations

import re
from io import StringIO
from pathlib import Path
from typing import Any

import yaml

from .defaults import VPC_CIDR_DEFAULT


# Service-name heuristics for type inference. Names compared lowercased.
_DB_HINTS = {
    "postgres": ("/var/lib/postgresql/data", "infrastructure"),
    "postgresql": ("/var/lib/postgresql/data", "infrastructure"),
    "mysql": ("/var/lib/mysql", "infrastructure"),
    "mariadb": ("/var/lib/mysql", "infrastructure"),
    "mongo": ("/data/db", "infrastructure"),
    "mongodb": ("/data/db", "infrastructure"),
}
_INFRA_HINTS = {"redis", "memcached", "rabbitmq"}
_WORKER_HINTS = ("celery", "worker", "beat", "scheduler", "cron", "sidekiq")


def scaffold_rc_yml(
    compose_path: Path | str,
    project: str | None = None,
    exclude: list[str] | tuple[str, ...] | None = None,
) -> str:
    """Read a docker-compose.yml and return rc.yml v2 content as a string.

    ``project`` defaults to the parent dir name of the compose file.
    ``exclude`` is a list of compose service names to drop from the
    deploy set — they appear under ``compose.exclude`` in the output so
    cli_v2.build_deploy_context honors the same shape it does for
    rc-up scaffolding. Useful for filtering dev-only sidecars
    (LinkedIn worker, ngrok, eval-app, docs builder, etc.) without
    having to hand-edit the resulting rc.yml.
    """
    compose_path = Path(compose_path)
    project = project or compose_path.parent.resolve().name or "myapp"
    excluded_set = {e.strip() for e in (exclude or []) if e and e.strip()}

    with compose_path.open() as f:
        compose = yaml.safe_load(f) or {}
    compose_services = compose.get("services") or {}

    # Validate the exclude list: every name must exist in compose, otherwise
    # the user has a typo and would silently get a no-op exclusion.
    unknown = excluded_set - set(compose_services.keys())
    if unknown:
        raise ValueError(
            f"--exclude lists service(s) not in compose: {sorted(unknown)}. "
            f"Known: {sorted(compose_services.keys())}"
        )

    services_section: dict[str, Any] = {}
    env_file_refs: list[tuple[str, list[str]]] = []  # [(svc_name, [paths]), ...]
    for svc_name, raw in compose_services.items():
        if svc_name in excluded_set:
            continue
        if not isinstance(raw, dict):
            continue
        overrides = _infer_service_overrides(svc_name, raw)
        if overrides:
            services_section[svc_name] = overrides
        envf = raw.get("env_file")
        if envf:
            paths = [envf] if isinstance(envf, str) else list(envf)
            env_file_refs.append((svc_name, paths))

    rc_yml: dict[str, Any] = {
        "version": 2,
        "project": project,
        "compose_file": compose_path.name,
        "provider": "ecs",
        "provider_config": {"ecs": {
            "region": "us-west-2",
            "cluster": f"{project}-cluster",
            "vpc_cidr": VPC_CIDR_DEFAULT,
            "default_launch_type": "FARGATE",
        }},
        "terraform": {
            "output_dir": "./terraform/${provider}",
            "backend": {"type": "local"},
        },
    }
    if services_section:
        rc_yml["services"] = services_section
    if excluded_set:
        # Stable order for diff-friendliness.
        rc_yml["compose"] = {"exclude": sorted(excluded_set)}

    # Render with a leading explanatory comment + env_file hints.
    out = StringIO()
    out.write("# Generated by `rc compose import`. Edit freely.\n")
    out.write("#\n")
    out.write("# Services in docker-compose.yml that aren't listed below still\n")
    out.write("# deploy with default cpu=256/memory=512 (see auto-import in\n")
    out.write("# cli_v2.build_deploy_context). Add a service entry here only to\n")
    out.write("# OVERRIDE its defaults.\n")
    out.write("#\n")
    out.write(f"# Source: {compose_path}\n")
    out.write("\n")
    yaml.safe_dump(rc_yml, out, sort_keys=False)
    if env_file_refs:
        out.write("\n# ---\n")
        out.write("# env_file refs detected in compose. Recommended path:\n")
        out.write("# move them to AWS Secrets Manager via rc.yml `secrets:` +\n")
        out.write("# `rc secrets push`. Stub:\n")
        out.write("#\n")
        out.write("# secrets:\n")
        seen: set[str] = set()
        for svc_name, paths in env_file_refs:
            for p in paths:
                if p in seen:
                    continue
                seen.add(p)
                stub_name = _derive_secret_name(p)
                out.write(f"#   - name: {stub_name}\n")
                out.write(f"#     source: file\n")
                out.write(f"#     path: {p}\n")
                out.write(f"#     # used by service {svc_name}\n")
    return out.getvalue()


def _infer_service_overrides(name: str, raw: dict[str, Any]) -> dict[str, Any]:
    """Best-effort defaults per service. Returns {} when nothing useful
    to suggest (the auto-import path will use cpu=256/memory=512)."""
    out: dict[str, Any] = {}
    lowered = name.lower()

    # Type inference by name.
    db_hint = _DB_HINTS.get(lowered)
    if db_hint:
        mount, type_ = db_hint
        out["type"] = type_
        out["volumes"] = [{
            "name": f"{lowered}-data",
            "mount": mount,
            # Common postgres uid hints. User adjusts per image flavor.
            "uid": 999,
            "gid": 999,
            "mode": "0700",
        }]
    elif lowered in _INFRA_HINTS or any(h in lowered for h in _INFRA_HINTS):
        out["type"] = "infrastructure"
    elif any(h in lowered for h in _WORKER_HINTS):
        out["type"] = "worker"

    # Public + port from compose ports[].
    ports = raw.get("ports") or []
    primary_port = _first_compose_port(ports)
    if primary_port is not None:
        # Workers shouldn't be public even if compose declares ports.
        if out.get("type") != "worker":
            out["public"] = True
            out["port"] = primary_port

    return out


def _first_compose_port(ports: list[Any]) -> int | None:
    """Extract the first containerPort from a compose ports[] entry.
    Same parsing rule as cli_v2._service_compose_ports for consistency."""
    for entry in ports:
        if isinstance(entry, dict):
            target = entry.get("target")
            if target is not None:
                try:
                    return int(target)
                except (TypeError, ValueError):
                    continue
            continue
        s = str(entry)
        if s.count(":") == 2:
            s = s.split(":", 1)[1]
        if ":" in s:
            _host, container = s.split(":", 1)
        else:
            container = s
        container = container.split("/", 1)[0].strip()
        if container.isdigit():
            return int(container)
    return None


def _derive_secret_name(path: str) -> str:
    """Default secret name from an env file path: strip dirs + leading dots.
    .envs/.production/.django → django"""
    stem = Path(path).name.lstrip(".")
    return re.sub(r"[^A-Za-z0-9._-]", "_", stem) or "secret"
